name: Test deploy # Workflow 이름
on: # Event 감지
    push:
        branches:
            - main
jobs: # Job 설정
    build:
        runs-on: ubuntu-latest
          
        steps:
            - name: Checkout source code. # Repo checkout
              uses: actions/checkout@v2

            - name: Check Node v # Node v 확인
              run: node -v

            - name: .env 세팅 
              run: |
               echo "REACT_APP_SERVER_URL=$REACT_APP_SERVER_URL" >> .env
               echo "REACT_APP_KAKAO_JAVASCRIPT_KEY=$REACT_APP_KAKAO_JAVASCRIPT_KEY" >> .env
               echo "REACT_APP_KAKAO_REST_API_KEY=$REACT_APP_KAKAO_REST_API_KEY" >> .env
               echo "REACT_APP_KAKAO_REDIRECT_URI=$REACT_APP_KAKAO_REDIRECT_URI" >> .env
              env:
               REACT_APP_SERVER_URL: ${{ secrets.REACT_APP_SERVER_URL }}
               REACT_APP_KAKAO_JAVASCRIPT_KEY: ${{ secrets.REACT_APP_KAKAO_JAVASCRIPT_KEY }}
               REACT_APP_KAKAO_REST_API_KEY: ${{ secrets.REACT_APP_KAKAO_REST_API_KEY }}
               REACT_APP_KAKAO_REDIRECT_URI: ${{ secrets.REACT_APP_KAKAO_REDIRECT_URI }}

            - name: Install Dependencies # 의존 파일 설치
              run: yarn install --frozen-lockfile

            - name: Build # React Build
              run: CI=false yarn build

            - name: Deploy                  # Upload build file to S3
              env:
                AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
                AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
              run: |
                  aws s3 cp --recursive --region ap-northeast-2 build s3://${{ secrets.S3_BUCKET_NAME }}
              
